core/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('register/', views.register, name='register'),
  path('login/', auth_views.LoginView.as_view(), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('account/', views.dashboard, name='dashboard'),
  path('recipes', views.RecipeView.as_view(), name='recipes'),
  path('categories/', views.GroupView.as_view(), name='categories'),
  path('recipe_set/', views.SearchResultView.as_view(), name='recipe_set'),
  path('posts/', views.PostsView.as_view(), name='posts'),
  path('add/', views.AddView.as_view(), name='add'),
  path('<slug:slug>/', views.SingleView.as_view(), name='single'),
  path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
  path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

vegfresh/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password=reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete'),
         name='password-reset-complete'),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image


class Ingredient(models.Model):
    IngName = models.CharField(max_length=30)
    IngType = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.IngName


class Core(models.Model):
    title = models.CharField(max_length=200)
    excerpt = models.TextField(null=True)
    category = models.CharField(max_length=10)
    cookTime = models.CharField(max_length=20)
    prepTime = models.CharField(max_length=20)
    ingredients = models.ManyToManyField(Ingredient)
    process = models.TextField(null=True)
    slug = models.SlugField(max_length=100, unique=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)
    thumb = models.ImageField(default='default.png', blank=True)

    def get_absolute_url(self):
        return reverse('core:single', args=[self.slug])

    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.title


class FoodGroup(models.Model):
    group_name = models.CharField(max_length=200)
    recipe = models.ManyToManyField(Core)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('core:single', args=[self.slug])

    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.group_name


class RecipeSet(models.Model):
    set_name = models.CharField(max_length=200)
    recipe = models.ManyToManyField(Core)
    published = models.DateField(default=timezone.now)

    def __str__(self):
        return self.set_name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='avatar.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Core
from .models import Profile


class PostForm(forms.ModelForm):
    class Meta:
        model = Core
        fields = "__all__"


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

core/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import Core
from .models import FoodGroup
from .models import RecipeSet
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


# Create your views here.

class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'


# Changed references location from 'Core' to 'RecipeIngredients'
class RecipeView(ListView):
    model = Core
    template_name = 'core/recipes.html'
    context_object_name = 'recipe'


class GroupView(ListView):
    model = FoodGroup
    template_name = 'core/category.html'
    context_object_name = 'category'


class SingleView(DetailView):
    model = Core
    template_name = 'core/single.html'
    context_object_name = 'post'


class PostsView(ListView):
    model = Core
    template_name = 'core/admin.html'
    context_object_name = 'post_list'


class AddView(CreateView):
    model = Core
    template_name = 'core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('core:posts')


class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')


class Delete(DeleteView):
    model = Core
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')
    template_name = 'core/confirm-delete.html'


class SearchResultView(ListView):
    model = RecipeSet

    template_name = 'core/set_result.html'
    context_object_name = 'recipe_set'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = RecipeSet.objects.filter(
            Q(set_name__exact=query)
        )
        return object_list


@login_required
def dashboard(request, *args, **kwargs):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save(*args, **kwargs)
            p_form.save(*args, **kwargs)
            messages.success(request, f'Your account has been updated.')
            return redirect('core:dashboard')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'account/dashboard.html', context)


def register(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save(*args, **kwargs)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('core:index')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})

templates/core/add.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container pt-5">
    <form method="post" class="bootstrap4" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field|as_crispy_field }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Submit
            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

templates/core/admin.html
{% extends 'core/base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand">Post Administration</div>
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:add' %}">New Post</a>
        </li>
    </ul>
</div>
</nav>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
        {% for post in post_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="https://via.placeholder.com/150x100" alt="Card image cap">
                    <div class="card-body">
                        <h4 class="lead"><a class="text-dark" href="{% url 'core:single' post.pk %}">{{ post.title }}</a></h4>
                        <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{ post.get_absolute_url }}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">View Post</a>
                                <a href="{% url 'core:edit' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Edit Post</a>
                                <a href="{% url 'core:delete' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Delete Post</a>
                            </div>
                            <small class="text-muted-9">9 Mins</small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/core/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <!-- Load the Style for Base -->
    <!-- Used for global changes -->
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/Base/style.css' %}">
    <!-- Load GoogleFont -->
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&family=Open+Sans&display=swap" rel="stylesheet">


    <!-- Load a local image as the webpage Icon -->
    <link rel="shortcut icon" type="image/png" href="{% static '/Branding/VegFreshIcon.ico' %}"/>
    <title>VegFresh - {{core.url}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--Font Awesome-->
    <script src="https://kit.fontawesome.com/9dcaf0cc45.js" crossorigin="anonymous"></script>
</head>
    <body>
    <!-- render header when base is extended -->
    {% include 'core/navbar.html' %}
    <!-- Display successful messages (i.e. user successfully logged in -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <!-- Allow content blocks to be utilised -->
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    {% include 'core/footer.html' %}
    </body>
</html>

templates/core/category.html
{% extends 'core/base.html' %}

{% block content %}

{% for foodgroup in category %}
<div class="album py-5">
    <div class="container">
    <h1>{{ foodgroup.group_name }}</h1><br>
    <div class="row">
            {% for recipe in foodgroup.recipe.all %}
        <div class ="col-md-4">
            <div class="card">
                {% load static %}
                <link rel="stylesheet" type="text/css" href="{% static 'CSS/Recipes/style.css' %}">
                <img class="card-img-top" src="{{ recipe.thumb.url }}" alt="Recipe card">
                <h4 class="card-title"><a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a></h4>
                <p>{{ recipe.excerpt }}</p>
                <div class="d-flex justify-content-between align-items-center">
                <div class="">
                    <small class="text-muted">
                        <i class="far fa-clock"></i> Prep time: {{ recipe.prepTime }}<br>
                        <i class="far fa-clock"></i> Cooking time: {{ recipe.cookTime }}<br>
                        {{ recipe.category }}</small>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endfor %}
    </div>
    </div>
</div>

{% endblock %}

templates/core/code_search.html
{% extends 'core/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container pt-5">
        <form action="{% url 'search_results' %}" method="get">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Enter your box code:</legend>
                <input name="q" type="text" placeholder="Search">
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>
</div>
{% endblock %}

templates/core/confirm-delete.html
{% extends 'core/base.html' %}
{% block content %}

<div class="container pt-5">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
</div>

{% endblock %}

templates/core/edit.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container pt-5">
    <form method="post" class="bootstrap4" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field|as_crispy_field }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Submit
            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

templates/core/footer.html
<div class="container">
<footer class="page-footer font-small blue">
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/"> VegFresh.com</a>
  </div>
</footer>
</div>

templates/core/index.html
{% extends 'core/base.html' %}
<!---->
    {% block content %}

<div class="container pt-5">
<div class="card text-center">
  <div class="card-header p-3 mb-2 bg-secondary text-white">
    <h5 class="card-title">Welcome to VegFresh!</h5>
  </div>
  <div class="card-body">
    <p class="card-text">Click the link below to Login or Signup!.</p>
      <button type="button" class="btn btn-info"><a class="nav-link"
            {% if user.is_authenticated %}
                <a href="{% url 'core:recipes' %}">New Recipes</a>
            {% else %}
                <a href="{% url 'core:register' %}">Sign Up!</a>
            {% endif %}
      </button>
  </div>
</div>
</div>

        <div class="container pt-5">
        <form action="{% url 'core:recipe_set' %}" method="get">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Enter your box code:</legend>
                <input name="q" type="text" placeholder="Search">
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>
</div>
    {% endblock content %}
{% include 'core/footer.html' %}

templates/core/navbar.html
<!doctype html>
<html lang="en">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Load the Style for Navbar -->
    <!-- Because Navbar is used on all pages be careful for overlap -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/Navbar/style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <div class="container">
  <a class="navbar-brand mb-0 h4" href="/">VegFresh</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}

        <li class="nav-link">
            <a class="nav-link" href="{% url 'core:recipe_set' %}">Box Code</a>
        </li>
      <li class="nav-link">
            <a class="nav-link" href="{% url 'core:recipes' %}">All Recipes</a>
      </li>
      <li class="nav-link">
            <a class="nav-link" href="{% url 'core:categories' %}">Categories</a>
      </li>
        {% endif %}
    </ul>
                    {% if user.is_authenticated %}
                        <div class="User-Banner">Welcome back, <a href="{% url 'core:dashboard' %}">{{request.user.username}}</a></div>
        {% endif %}
      <li class="nav-link">
      <button type="button" class="btn btn-outline-info btn-sm">
          <a class="nav-link"
            {% if user.is_authenticated %}
                <a href="{% url 'core:logout' %}">LOG OUT</a>
            {% else %}
                <a href="{% url 'core:login' %}">LOG IN</a>
            {% endif %}
      </button>
      </li>
  </div>
</nav>
    </div>
  <body>

templates/core/recipes.html
{% extends 'core/base.html' %}

{% block content %}

<div class="album py-5">
    <div class="container">
    <div class="row">
        {% for core in recipe %}
        <div class ="col-md-4">
            <div class="card">
                {% load static %}
                <link rel="stylesheet" type="text/css" href="{% static 'CSS/Recipes/style.css' %}">
                <img class="card-img-top" src="{{ core.thumb.url }}" alt="Recipe card">
                <h4 class="card-title"><a href="{{ core.get_absolute_url }}">{{ core.title }}</a></h4>
                <p>{{ core.excerpt }}</p>
                <div class="d-flex justify-content-between align-items-center">
                <div class="">
                    <small class="text-muted">
                        <i class="far fa-clock"></i> Prep time: {{ core.prepTime }}<br>
                        <i class="far fa-clock"></i> Cooking time: {{ core.cookTime }}<br>
                        {{ core.category }}</small>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>
</div>

{% endblock %}

templates/core/scratchpad.html
{% for foodgroup in category %}
{{ foodgroup.group_name }}
{% for recipe in foodgroup.recipe.all %}{{ recipe.title }}<br/>{{ recipe.thumb.url }}{% endfor %}
{% endfor %}

templates/core/set_result.html
{% extends 'core/base.html' %}
{% block content %}
{% for RecipeSet in recipe_set %}
<div class="album py-5">
    <div class="container">
    <h1>{{ RecipeSet.set_name }}</h1><br>
    <div class="row">
            {% for recipe in RecipeSet.recipe.all %}
        <div class ="col-md-4">
            <div class="card">
                {% load static %}
                <link rel="stylesheet" type="text/css" href="{% static 'CSS/Recipes/style.css' %}">
                <img class="card-img-top" src="{{ recipe.thumb.url }}" alt="Recipe card">
                <h4 class="card-title"><a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a></h4>
                <p>{{ recipe.excerpt }}</p>
                <div class="d-flex justify-content-between align-items-center">
                <div class="">
                    <small class="text-muted">
                        <i class="far fa-clock"></i> Prep time: {{ recipe.prepTime }}<br>
                        <i class="far fa-clock"></i> Cooking time: {{ recipe.cookTime }}<br>
                        {{ recipe.category }}</small>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endfor %}
    </div>
    </div>
</div>
{% endblock %}

templates/core/single.html
{% extends 'core/base.html' %}
{% block content %}

<!-- Load in static file for Single -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/Single/style.css' %}">

    <div class="container pt-5">
<div class="card mb-3">
            <img class="card-img-top" src="{{ post.thumb.url }}" alt="Card image">
  <div class="card-body">
  <div class="row">
        <div class="col-sm border-right">
        <h5 class="card-title">{{ post.title }}</h5>
        <small><i class="far fa-clock"></i> Prep time: {{ post.prepTime }}</small><br>
        <small><i class="far fa-clock"></i> Cooking time: {{ post.cookTime }}</small><br>
        <div class="card-header">
        Ingredients
        </div>
      <ul class="list-group list-group-flush">
          {% for ingredients in post.ingredients.all %}
            <li class="list-group-item">{{ ingredients }}</li>
          {% endfor %}
        </ul>
        </div>
  <div class="col-sm">
      <h5 class="card-title">Steps:</h5>
      <p class="card-text">{{ post.process|linebreaks }}</p>
      </div>
  </div>
  <div class="card-footer">
      <p class="card-text"><small class="text-muted">Recipe published: {{ post.published }}</small></p>
  </div>
</div>
</div>
    </div>
{% endblock %}